[package]
name = "cocos-renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
bitflags = { version = "2.9" }
downcast-rs = { workspace = true }
auto_impl = { workspace = true }
wgpu = { workspace = true }
